name: macOS Intel Scrap Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'libs/scrap/**'

jobs:
  build:
    name: x86_64-apple-darwin (scrap)
    runs-on: macos-14
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies via Homebrew
      run: |
        brew install libvpx libyuv aom opus

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
      with:
        toolchain: stable
        targets: x86_64-apple-darwin

    - name: Build scrap library
      run: |
        cargo build -p scrap --target x86_64-apple-darwin